name: Checkout Test.
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
env:
  src_repo: yuki-shinohara-biz/test-repo-src
  dest_repo: yuki-shinohara-biz/test-repo-dest
jobs:

  Pull_from_other_Repo:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - name: (For Test Only!) Set current datetime as env variable
        env:
          TZ: 'Asia/Tokyo'
        run: echo "CURRENT_DATETIME=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Checkout Source Repository
        uses: actions/checkout@v3
        with:
          repository: ${{ env.src_repo }}
          ref: main
          path: src

      - name: Checkout Destination Repository
        uses: actions/checkout@v3
        with:
          repository: ${{ env.dest_repo }}
          ref: main
          path: dest

      - name: Build Frontend
        run: |
          cd ${{ github.workspace }}/src/test
          npm run build
          cp -r ${{ github.workspace }}/src/test/dist ${{ github.workspace }}/dest/front

      - name: Create New Brunch To Destination
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd ${{ github.workspace }}/dest
          git switch -c test/actions_${{ env.CURRENT_DATETIME }}
          git config user.name  github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "Github Actions build"
          git push -u origin test/actions_${{ env.CURRENT_DATETIME }}
