name: Checkout Test.
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Pull_from_other_Repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v3
        with:
          repository: yuki-shinohara-biz/test-repo-src
          ref: main
          path: src

      - name: Checkout Destination Repository
        uses: actions/checkout@v3
        with:
          repository: yuki-shinohara-biz/test-repo-dest
          ref: main
          path: dest

      - name: Build
        run: |
          cd ${{ github.workspace }}/src
          cat README.md
          cd ${{ github.workspace }}/dest
          cat README.md

      - name: Create New Brunch To Destination
        run: pwd
