name: Checkout Test.
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Pull_from_other_Repo:
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write

    steps:
      - name: (For Test Only!) Set current datetime as env variable
        env:
          TZ: 'Asia/Tokyo'
        run: echo "CURRENT_DATETIME=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Checkout Source Repository
        uses: actions/checkout@v3
        with:
          repository: yuki-shinohara-biz/test-repo-src
          ref: main
          path: src

      - name: Checkout Destination Repository
        uses: actions/checkout@v3
        with:
          repository: yuki-shinohara-biz/test-repo-dest
          ref: main
          path: dest

      - name: Build
        run: |
          cd ${{ github.workspace }}/src
          cat README.md
          cd ${{ github.workspace }}/dest
          cat README.md

      - name: Create New Brunch To Destination
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd ${{ github.workspace }}/dest
          git switch -c test/actions_${{ env.CURRENT_DATETIME }}
          git push -u origin test/actions_${{ env.CURRENT_DATETIME }}
