name: Build Test
run-name: Build by ${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      releaseVerion:
        description: 'リリースするバージョン名を指定'
        required: true
        type: string

env:
  src_repo: yuki-shinohara-biz/test-repo-src
  dest_repo: yuki-shinohara-biz/test-repo-dest
  node_js_version: "14.18.0"
  frontend_dir_name: test
jobs:

  Build_For_Release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:

      - name: (For Test Only!) Set current datetime as env variable
        env:
          TZ: 'Asia/Tokyo'
        run: echo "CURRENT_DATETIME=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Setup Node.js ${{ env.node_js_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_js_version }}

      - name: Checkout Source Repository
        uses: actions/checkout@v3
        with:
          repository: ${{ env.src_repo }}
          ref: main
          path: src

      - name: Checkout Destination Repository
        uses: actions/checkout@v3
        with:
          repository: ${{ env.dest_repo }}
          ref: main
          path: dest

      - name: Build Frontend
        run: |
          cd ${{ github.workspace }}/src/${{ env.frontend_dir_name }}
          npm install
          npm run build
          cp -r ${{ github.workspace }}/src/${{ env.frontend_dir_name }}/dist ${{ github.workspace }}/dest/front

      - name: Create New Brunch To Destination
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd ${{ github.workspace }}/dest
          git switch -c release/${{ inputs.releaseVerion }}_${{ env.CURRENT_DATETIME }}
          git config user.name  github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "Github Actions build"
          git push -u origin release/${{ inputs.releaseVerion }}_${{ env.CURRENT_DATETIME }}

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd ${{ github.workspace }}/dest
          gh pr create --fill -B main -t "Pull Request For Release "${{ inputs.releaseVerion }} -b "build test"
