name: Checkout Test.
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Pull_from_other_Repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
        with:
          repository: yuki-shinohara-biz/test-repo-src
          ref: main

      - name: Build
        run: echo "ls -l"
